### ISSUE TITLE
Coretext + Skia Possible Issue.

### ISSUE THREAD

**Issue by PhilCK** [behdad/harfbuzz#220]
Hi,

Quite new to Harfbuzz so I might be missing something. We use skia to get our font information, however when ever a font is renderered that only has a mort table we get missing glyphs.

If I load up the font directly using harfbuzzes interface it all works fine, but we cache font information locally.

```cpp
// This works
hb_face_t * face = hb_face_create_for_tables (reference_table, CGFontRetain (dfont), (hb_destroy_func_t) CGFontRelease);

// This doesn't
hb_face_t * face = hb_face_create_for_tables (reference_table, CGFontRetain (dfont), nullptr);
```

I think it comes down to this code. In `hb-coretext.cc`
```cpp
  if (face->destroy == (hb_destroy_func_t) CGFontRelease)
  {
    data = CGFontRetain ((CGFontRef) face->user_data);
  }
```

When the destroy callback comes back for the hb_face I can see that the shaper is OT if I didn't set `CGFontRelease` and CoreText if I did.

Is this correct behaviour?

**Comment by behdad** [comment]
Correct.  If you use CGFontRelease, HarfBuzz will know that you are using a CGFont as userdata and will use it.  Otherwise, your reference_table should return the entire font blob if called with tag=0.  If you don't implement that, then HarfBuzz has no way to create a CGFont and as such won't be able to use the coretext shaper.

**Comment by PhilCK** [comment]
Thanks Behdad, We went down the tag=0 route.
