### ISSUE TITLE
VS2013 & VS2015 builds fail.

### ISSUE THREAD

**Issue by DroidSparks** [behdad/harfbuzz#339]
According to the README.txt file, it says to do nmake /f Makefile.vc CFG=[release|debug] [PREFIX=...] <option1=1 option2=1 ...>

I try that and end up with an error, as shown here:
```

D:\harfbuzz\win32>nmake /f Makefile.vc CFG=debug DIRECTWRITE=1

Microsoft (R) Program Maintenance Utility Version 14.00.23918.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1073: don't know how to make 'config.h.win32'
Stop.
```

Tried with both VS2013 & VS2015, both have the same output.
If I copy config.h.win32.in to config.h.win32, it does advance, but then gets stuck on:

```
hb-blob.cc
D:\harfbuzz\src\hb.h(45) : fatal error C1083: Cannot open include
 file: 'hb-version.h': No such file or directory
```
There is a hb-version.h.in but it looks like it needs to generate some values within it.
It is not clear at all how to do this using Visual Studio.

**Comment by ebraminio** [comment]
Same as #319, you should use nmake on a [release tarball](https://www.freedesktop.org/software/harfbuzz/release/) rather than github source, even the fact you can do the release step [by yourself](https://github.com/behdad/harfbuzz/blob/master/appveyor.yml#L31) on a Windows machine also. Good news is harfbuzz will soon [hopefully] be added to [vcpkg](https://github.com/Microsoft/vcpkg/pull/132) and installing it will become one command :)
