### ISSUE TITLE
Broken Kannada shaping?

### ISSUE THREAD

**Issue by brawer** [behdad/harfbuzz#347]
For NotoSerifKannada-Regular.ttf, HarfBuzz emits broken output while CoreText output looks good for the same font. This might be a bug in HarfBuzz. However, it might also be that CoreText has a bug in its Kannada shaping; I don’t know if Noto’s font designers have tested their font on multiple OpenType implementations or just on CoreText. So it might well be that the font (and CoreText) are buggy. If somebody who knows more about Kannada shaping could analyze this, it would be great.

I’ve added this as a [test case](https://raw.githack.com/icu-project/text-rendering-tests/master/reports/FreeStack.html#SHKNDA-1) to Unicode’s [text rendering test suite](https://github.com/icu-project/text-rendering-tests), using CoreText to generate the expected renderings. Should it turn out that the HarfBuzz implementation is correct and CoreText (and the Noto font) are both wrong, I’ll of course adjust the test suite.

<img width="1027" alt="screenshot of broken Kannada shaping" src="https://cloud.githubusercontent.com/assets/1527880/19263363/42190c52-8f9c-11e6-861b-8c349d1ff836.png">

See https://github.com/googlei18n/noto-fonts/issues/759 for the corresponding bug report on the NotoSerifKannada font.

**Comment by KrasnayaPloshchad** [comment]
I’m sure this is a bug in HarfBuzz, see the discussions on #341.

**Comment by lianghai** [comment]
I wrote GSUB rules for all Noto Serif Indic fonts, and I can confirm it's a HarfBuzz issue. HarfBuzz's handling of the "GDEF" table seems to be nonstandard, which leads to this issue.

Noto Serif Kannada relies on `lookupflag IgnoreMarks;` for some lookups to work properly. The lookup of rules `sub knKA knmI by knKI;` etc has `lookupflag IgnoreMarks;` too (for skipping Nukta), however HarfBuzz wrongly considers vowel signs are marks (a derivation from UCD?) despite that in the "GDEF" table vowel signs are not defined as GDEF marks.

A patched Noto Serif Kannada with a minimal change (setting the `<LookupFlag value="8"/>` in `<Lookup index="4">` to `<LookupFlag value="0"/>`) demonstrates how this works:
[NotoSerifKannada-Regular-patched.ttf.zip](https://github.com/behdad/harfbuzz/files/654444/NotoSerifKannada-Regular-patched.ttf.zip)

**Comment by lianghai** [comment]
@KrasnayaPloshchad I don't think this issue is related to #341 though.

**Comment by lianghai** [comment]
While patching SamsungOne fonts I've noticed HarfBuzz's exact issue seems to be:

When a Unicode-mapped glyph's GDEF class is undefined in the GDEF table, HarfBuzz defaults its GDEF class to a value derived from UCD (eg, `Mn` becomes GDEF class 3 "mark glyph").

However, according to the OT spec, https://www.microsoft.com/typography/otspec/GDEF.htm —

> The font developer does not have to classify every glyph in the font, but any glyph not assigned a class value falls into Class zero (0).

— Which is indeed the common behavior of text engines (including earlier versions of HarfBuzz, eg, 0.9.40 and 1.0.5, according to Samsung's report). With the expected behavior of defaulting to 0, any glyph not assigned a class value in the GDEF table should not be ignored by `lookupflag IgnoreMarks;` (ignoring class 3).

Now the workaround for me is to patch the fonts by assigning non mark glyphs the class value of 1 "base glyph", like what happened (or was intended?) to have been done in Nirmala UI.

**Comment by behdad** [comment]
@lianghai The GDEF behavior you mention is definitely not expected.  HarfBuzz only fills in GDEF classes from Unicode data if there is no GDEF table present...

Ugh. Now I see that this was changed in March, in: 69f9fbc4200442a35484d3c790ae8f4979be5d60
I suppose I can special-case Indic-like shapers to disable this and use the previous logic.

**Comment by lianghai** [comment]
@behdad Ah, I see… Though, given the clearly defined behavior of "any glyph not assigned a class value falls into Class zero (0)" in the OT spec, should the special case be actually Hebrew that does synthesize GDEF glyph class (instead of Indic-like shapers that do not)?

**Comment by behdad** [comment]
@lianghai Yeah, I'm going to revert this, and make hebrew shaper ignore GDEF and GPOS (and use fallback for both) if GPOS Hebrew script system is not found.

**Comment by MayuraVerma** [comment]
Is this fixed now? 
When this change will reflect in Chrome browser?

**Comment by MayuraVerma** [comment]
Thank you for addressing this issue.

I see that we have resolved this. 

But when will we see this updated in Chrome? when do they incorporate the updated harfbuzz? 

Could you please help me understand what version of harfbuzz is currently used in chrome.

**Comment by behdad** [comment]
> Could you please help me understand what version of harfbuzz is currently used in chrome.

I don't know, but it should eventually make it to Chrome Stable. No further action is needed.

@drott yet another nag to have HarfBuzz version visible in chrome://version or whereever...

**Comment by drott** [comment]
https://chromium.googlesource.com/chromium/src/ can be used to look at the harfbuzz version that Chromium is compiled with. The first release version of HarfBuzz after e2b8780 is 1.4.0. In Chrome 57 [we have rolled to HarfBuzz 1.4.1](https://chromium.googlesource.com/chromium/src/+/57.0.2987.88/third_party/harfbuzz-ng/README.chromium). @MayuraVerma you can try with Chrome Beta, which is at version 57.

**Comment by MayuraVerma** [comment]
@drott Thank you. This is with the Chrome beta version. Finally NotoSerifKannada is rendering text correctly with updated harfbuzz.

![screen shot 2017-03-04 at 4 08 05 pm](https://cloud.githubusercontent.com/assets/14062593/23582684/52334074-00f5-11e7-9a1a-61de40cccdf8.png)

Few questions: It could be off-topic, please bear with me.

1. Could we request chrome browser in iOS to use harfbuzz. Apple coretext is very buggy with Indian languages.
2. If chrome browser in iOS can change fonts for specific language, so user can use "Google Noto Sans/Serif fonts" instead of Apple fonts for Indian languages (which is again super buggy). In mac, I am using "advanced font settings" to achieve it. If this can be embedded in both desktop and mobile versions, it will save a lot of headache for users from India.

Thanks.

**Comment by brawer** [comment]
> Apple coretext is very buggy with Indian languages.

@MayuraVerma, do you know specific Unicode sequences that are broken? Feel free to add test cases to [Unicode’s text rendering texts](https://github.com/unicode-org/text-rendering-tests). Or simply [file a bug](https://github.com/unicode-org/text-rendering-tests/issues) with a list of strings that can be converted to test cases. Apple keeps an eye on the Unicode test suite, and they’ve fixed bugs in the past.

**Comment by MayuraVerma** [comment]
@brawer sure, I will do that.

**Comment by drott** [comment]
> Few questions: It could be off-topic, please bear with me.
> 
> Could we request chrome browser in iOS to use harfbuzz. Apple coretext is very buggy with Indian languages.

Chrome on iOS uses Safari's WebKit as layout engine, this is not something we can currently change.

> If chrome browser in iOS can change fonts for specific language, so user can use "Google Noto Sans/Serif fonts" instead of Apple fonts for Indian languages (which is again super buggy). In mac, I am using "advanced font settings" to achieve it. If this can be embedded in both desktop and mobile versions, it will save a lot of headache for users from India.

For changing default fonts in iOS Chrome (which would still go through CoreText), I would suggest to file a feature request on [crbug.com](https://crbug.com). 

Otherwise, @brawer 's suggestion is probably your best bet for getting CoreText bugs fixed.

**Comment by MayuraVerma** [comment]
@drott 

is the limitation in iOS that doesn't allow browsers uses its know text engine? 

For changing default fonts: I will submit the cr right away. Besides Apple coretext issue for Kannada language, Apple system default font KannadasangamMN (TTF) has a lot bugs in it. 

Solving font issue with google fonts and reporting issues CoreText is right way to proceed for me. Apple is slowly changing TTF with new set of OTF for Indian languages. When they do that Coretext engine should not have issues.
