### ISSUE TITLE
Rendering for Tibetan long vowel U is broken

### ISSUE THREAD

**Issue by domschl** [behdad/harfbuzz#417]
On Linux and Android, the Tibetan syllable U (ཨཱུ) is rendered incorrectly.

The following site shows the browser-output when rendering hUM and U, together with bitmaps for the correctly rendered glyphs: [Test-site](http://digitaltibetan.org/index.php/Tibetan_Unicode_Test_Page#Harfbuzz_test)

Affected are:
* Android (tested with 7.1.2beta)
* Linux (tested with harfbuzz 1.4.2)
* macOS & Chrome: rendering seems ok within macOS fonts Kokonor and Kailasa, but breaks with all other Tibetan fonts tested.

**Comment by KrasnayaPloshchad** [comment]
Confirmed on Windows 10. 

Firefox 51.0.1
![1](https://cloud.githubusercontent.com/assets/10364351/22862948/1829ad28-f173-11e6-8341-6606ed1ba142.PNG)
![2](https://cloud.githubusercontent.com/assets/10364351/22862946/13de5a98-f173-11e6-845b-5ec7032132e4.PNG)
BabelPad 9.0.0.3
![3](https://cloud.githubusercontent.com/assets/10364351/22863010/141e2492-f174-11e6-8a70-cd7513c1d968.PNG)
![4](https://cloud.githubusercontent.com/assets/10364351/22863012/14303902-f174-11e6-965b-7adfa3baa449.PNG)
LibreOffice 5.3
![5](https://cloud.githubusercontent.com/assets/10364351/22863013/14b95728-f174-11e6-974c-43a3b3df07bb.PNG)
![6](https://cloud.githubusercontent.com/assets/10364351/22863011/141eee90-f174-11e6-8044-3ef131eccbd1.PNG)

What I got surprised are: with Microsoft Himalaya the vowel signs are upside down, with Jomolhari one vowel sign failed to join. Since HarfBuzz is also intergrated in LibreOffice, this problem become more wide spread that need to pay more attentions to.

**Comment by eroux** [comment]
With latest git, running

```
./hb-view --output-format=png --output-file=U.png --language=tibt --script=tibt /usr/share/fonts/truetype/noto/NotoSansTibetan-Regular.ttf ཨཱུ
```

gives

![u](https://cloud.githubusercontent.com/assets/60868/24321480/1e662568-114e-11e7-80fc-9a2a3b21d369.png)

(which is wrong)

**Comment by eroux** [comment]
After a git bisect, I can tell that the bug has been introduced in 2f560ee44b7b08683e8e6955fe3b95187e8bda32

**Comment by domschl** [comment]
@eroux : Nice find! Just changing the one line back seems to fix the rendering of long vowel U for me. I have tested on Arch linux, Chrome and LibreOffice work fine. Of course this needs to be checked by the original author of 2f560ee44b7b08683e8e6955fe3b95187e8bda32, don't know if this would break something else.

**Comment by jungshik** [comment]
@behdad, it seems that matching uniscribe breaks other fonts. What would be a resolution?

**Comment by eroux** [comment]
@jungshik what do you mean specifically? Is that related to Tibetan or is it a more general statement?

**Comment by jungshik** [comment]
@eroux, I'm referring to [HarfBuzz commit  2f560ee](https://github.com/behdad/harfbuzz/commit/2f560ee44b7b08683e8e6955fe3b95187e8bda32)  which changed the behavior of Tibetan shaper to match the behavior of Uniscribe. That commit was found by @domschl  with bisecting.

**Comment by eroux** [comment]
What I meant is: what are you referring to when you say

- "matching uniscribe": is it this change in particular or the general idea of matching uniscribe?
- "breaks other fonts": what exactly does get broken? which fonts? with what unicode sequence?

**Comment by domschl** [comment]
It was @eroux who found the cause of the problem. Currently, we are suggesting a possible fix (#443) which would repair the Tibetan, while keeping the improvements that were intended with 2f560ee44b7b08683e8e6955fe3b95187e8bda32 . The fix requires a thorough review, which will be the next step.

**Comment by jungshik** [comment]
> "matching uniscribe": is it this change in particular or the general idea of matching uniscribe?

My comment is in this bug so I meant this particular issue. 

> "breaks other fonts": what exactly does get broken? which fonts? with what unicode sequence?

This bug is about that, no? Microsoft Himalaya is fine, but other Tibetan fonts do not work as expected.

**Comment by eroux** [comment]
I'm still unsure what your point is... asking it in a different way, do you think https://github.com/behdad/harfbuzz/pull/443 has some bugs left or is it fine for you?

**Comment by eroux** [comment]
Thanks a lot for the fix!

**Comment by domschl** [comment]
Tx all! the long-U is back!

**Comment by KrasnayaPloshchad** [comment]
This bugfix would landing in Firefox 56, I hope LibreOffice would following soon.

**Comment by KrasnayaPloshchad** [comment]
>I hope LibreOffice would following soon. 

TDF Bugzilla: https://bugs.documentfoundation.org/show_bug.cgi?id=109142
