### ISSUE TITLE
Possible to apply feature lookups to a buffer of glyphs?

### ISSUE THREAD

**Issue by manuel-rhdt** [behdad/harfbuzz#420]
If you get a list of glyph indices without using harfbuzz, is it still possible to use harfbuzz for applying substitution and/or positioning features to this list of glyphs?

E.g. I have an array of the 'f' and the 'i' glyph indices for a certain font and I want to use harfbuzz to get the glyph index for the 'fi' ligature. Is that possible?

**Comment by khaledhosny** [comment]
This is not currently possible, `hb_shape()` will assert if the buffer type is not Unicode. There is an old [thread on the mailing list](https://lists.freedesktop.org/archives/harfbuzz/2011-April/001200.html) with a suggested way to do what you want (the subclassing part is already possible now).

**Comment by manuel-rhdt** [comment]
Thank you, this is a usable workaround for my problem however it feels hacky. Would it make sense to add an API to harfbuzz that applies a user-defined selection of lookups to a supplied buffer of glyphs/chars? 

My use case is applying the 'flac' feature to glyphs obtained by creating a glyph assembly using the MATH table. I can imagine other use cases of this API for applying specific feature lookups after basic shaping has already been done so that possibly no full reshape is needed?

**Comment by behdad** [comment]
I'm willing to add a couple of functions that give direct access to single substitutions and single positioning.  Those can be used for 'aalt' and 'opsz' features. That will be useful for your 'flac' case **most** of the time, but spec says "Recommended implementation: Single substitution", ie. it *can* be a contextual lookup, in which case the hacky way above is still my recommendation. It's ten lines to implement and does the job perfectly. I don't want to make it easier to do these kinds of stuff because most of the time when people think they need this they are wrong. Your MATH table case is one of the few legitimate uses for this feature.

**Comment by khaledhosny** [comment]
I think one can safely skip `flac` feature for assemblies, I doubt there are any fonts out there that use it for any thing but simple accents (and if I were to build a math font that wants to apply `flac` to assemblies, I’d build it so that `flac` maps to the alternate accent glyph, then that glyph would have a horizontal assembly, not the other way around). So one should simply apply `flac` feature when initially shaping the buffers for math accents that need it.

Also since math accents are not (and should not be) positioned by `GPOS`, they should be shaped separately from their bases to avoid any unwanted interaction (which also mean that a contextual `flac` wouldn’t work), so the base should be shaped first and it height measured and if it ≥ `FlattenedAccentBaseHeight` then the accent should be shaped with `flac`, otherwise not.

**Comment by manuel-rhdt** [comment]
Yes, I agree with you that it would make more sense to make `flac` map to an alternate accent glyph that has a horizontal assembly instead of the other way round. However Microsoft's Cambria Math, one of the most used and best looking math fonts out there does exactly that. Since its the first opentype math font ever created, I think this should be supported...

Also I would agree with Behdad that exposing substitution functionality separate from shaping would probably be misused, so I think the workaround using font-funcs is not *that* bad. :)

**Comment by khaledhosny** [comment]
Just checked Cambria, and you are right. I guess the custom font functions is the way to go then.

**Comment by behdad** [comment]
> Also I would agree with Behdad that exposing substitution functionality separate from shaping would probably be misused, so I think the workaround using font-funcs is not that bad. :)

Ok, I'll close this for now then.  Let us know how it goes and we'll figure out something if it doesn't work out.
