### ISSUE TITLE
Shouldn’t default ignorables be 0 width even when preserved

### ISSUE THREAD

**Issue by khaledhosny** [behdad/harfbuzz#441]
I was testing with the soft hyphen and most fonts seem to give it positive width, but I think setting `HB_BUFFER_FLAG_PRESERVE_DEFAULT_IGNORABLES` should not change the layout:

    $ hb-unicode-encode U+0061,U+00AD,U+0062 | hb-shape NotoSans-Regular.ttf
    [gid68=0+1149|gid3=1+0|gid69=2+1260]

    $ hb-unicode-encode U+0061,U+00AD,U+0062 | hb-shape NotoSans-Regular.ttf --preserve-default-ignorables
    [gid68=0+1149|gid111=1+659|gid69=2+1260]

And may be even setting x offset to minus half advance width so it looks visually centered.

**Comment by khaledhosny** [comment]
Looks easy, I can make a PR if we agree this is desirable.

**Comment by jfkthame** [comment]
I'm not sure I agree with this. When harfbuzz is treating default-ignorables as ignorable (i.e. it's implementing their default behavior), it makes them zero-width *and* invisible; but if it's not implementing that behavior, then I think it should respect whatever the font designer has provided. If this is used as part of a "show invisibles" rendering mode, it may well be necessary to let the default-ignorables have a non-zero width in addition to a visible glyph; otherwise they'll just overstrike adjacent glyphs and may well be illegible or even invisible as a result.

**Comment by khaledhosny** [comment]
My understand is that this flag was supposed to be used for “show control character”-like behavior, and the applications that implement such a feature implement it in a way that does not change layout. LibreOffice the soft hyphen indeed overstrikes adjacent characters (but it is also highlighted with gray background color).

**Comment by behdad** [comment]
I'm divided between the two sides. Maybe we should change to an enum?

**Comment by jfkthame** [comment]
I almost suggested that, as I was feeling a bit divided too....

I think, though, that any application that actually wants a "show control chars" type of feature will need to implement something quite different, and trying to simply use this flag is doomed to failure. The problem is that many fonts won't provide glyphs at all; some may provide only blank glyphs; and even when visible glyphs exist, they may be such a variety of graphical representations that they aren't reliable as a means to show the user what controls are present.

So the "show invisibles" use case isn't much use, I suspect. I think this flag has little real use except for debugging harfbuzz itself, or perhaps debugging fonts, where it might sometimes be useful to be able to see in the output where the default-invisibles ended up (e.g. after reordering). And for that purpose, there's no need to zero their widths and make them harder to see in the hb-view result.

**Comment by khaledhosny** [comment]
I think @jfkthame has a point here. We probably best leave things as they are now.
