### ISSUE TITLE
Support AAT font variation

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#499]
Apple AAT have font variation for a long times before OpenType font variation introduced.

**Comment by twardoch** [comment]
OpenType font variation is backwards-compatible with AAT font variation, or, more specifically, with TrueType GX Variation. In a way, platforms that support OpenType Variations also implicitly support TrueType GX Variations — just like platforms that support OpenType also implicitly support TrueType. 

Except for the AAT-layout-specific tables such as [`morx`](https://github.com/behdad/harfbuzz/issues/322) and `kerx`, Skia (for a long time the only publicly-available variable AAT font) should work in platforms that support OpenType Variations. Skia does not include the `STAT` table required by Windows for supporting OpenType Variations, but since Skia is only licensed to be bundled with macOS and iOS, it’s a non-issue. There were only a handful other AAT variable fonts made, and most of them have already been upgraded to support OpenType Variations. The required changes are minimal.

**Comment by KrasnayaPloshchad** [comment]
So this issue can be closed if HarfBuzz is proves working with AAT variable fonts.
