### ISSUE TITLE
Dotted circle between instances of U+1A7F

### ISSUE THREAD

**Issue by dscorbett** [behdad/harfbuzz#525]
U+1A7F TAI THAM COMBINING CRYPTOGRAMMIC DOT may appear multiple times on the same syllable. ⟨ᨠ᩿᩿᩿᩿᩿⟩ has five cryptogrammic dots, and dotted circles are inserted before all but the first. No dotted circles should be inserted.

**Comment by jfkthame** [comment]
U+1A7F has Indic Syllabic Category = Syllable_Modifier, which is the same category as 1A7B..1A7C, which look as though they should probably be restricted to a single occurrence. Sure enough, the USE cluster regex only accepts a single (optional) trailing FM.

(Also, the USE model appears to only recognize Consonant Final Modifier (FM) as appearing at the top of the cluster, whereas U+1A7F appears below.)

A workaround for the time being may be to override the category of 1A7F to treat it as a Final Consonant Below instead of Modifier; AFAICS this won't clash with anything else Tai Tham is using, and will allow it to be repeated.
