### ISSUE TITLE
Running git update for harfbuzz fail

### ISSUE THREAD

**Issue by dooley2009** [behdad/harfbuzz#591]
We have had some issues over at media-autobuild_suite

https://github.com/jb-alvarado/media-autobuild_suite/issues/620

Thought you guys would like to know.

**Comment by khaledhosny** [comment]
```
autogen failed. Check C:/Optimizing-Main/Video/media-autobuild-suite/build/harfbuzz-git/ab-suite.autogen.log
```

Looks like autogen failed, but the referenced log file is missing from that ssO9.zip.

**Comment by ebraminio** [comment]
Per CI bots and as the suggested fix on [this](https://github.com/jb-alvarado/media-autobuild_suite/issues/620#issuecomment-340706755), this is because harfbuzz is in inconsistent state, that usually don't happen much. I hope @behdad can fix the hb-uniscribe/hb-coretext soon but I wonder why you need hb-uniscribe as it seems it is enabled [here](https://github.com/jb-alvarado/media-autobuild_suite/blob/c1a36d60eb62f2e612c35cdaa0cc977b63368f63/build/media-suite_compile.sh#L163), can you disable uniscribe backend just like directwrite? Most projects don't need them as it is disabled on Chrome/Chromium also.

**Comment by behdad** [comment]
> I hope @behdad can fix the hb-uniscribe/hb-coretext issue soon

What issue are you referring to?

**Comment by ebraminio** [comment]
> What issue are you referring to?

[1](https://travis-ci.org/behdad/harfbuzz/jobs/295039536#L3468) and [2](https://ci.appveyor.com/project/behdad/harfbuzz/build/1.0.697/job/dr1ujlntxafeqbej#L142)

**Comment by behdad** [comment]
Weird.  Why do we not get emails anymore when Travis fails?

**Comment by behdad** [comment]
Ok, let's see if 98acdde3c6bd0745c3cbfb510e82fbd87ebd1a33 fixes them.

**Comment by ebraminio** [comment]
So this can be closed, @dooley2009 let us know if that will fix your issue. Thanks
